CREATE TABLE OBSTACLES.ESTADO (
    ID BIGINT NOT NULL,
    NOME CHARACTER VARYING (255) NOT NULL,
    UF CHARACTER VARYING (2) NOT NULL,
    UUID UUID NOT NULL,
    CONSTRAINT ESTADO_PK PRIMARY KEY (ID)
);

CREATE TABLE OBSTACLES.CIDADE (
    ID BIGINT NOT NULL,
    NOME CHARACTER VARYING (255) NOT NULL,
    CIDADE_URL CHARACTER VARYING (255) NOT NULL,
    UUID UUID NOT NULL,
    ESTADO_ID BIGINT NOT NULL,
    CONSTRAINT CIDADE_PK PRIMARY KEY (ID),
    CONSTRAINT ESTADO_CIDADE_ID_FK FOREIGN KEY (ESTADO_ID) REFERENCES OBSTACLES.ESTADO (ID)
);

CREATE TABLE OBSTACLES.OBSTACULO (
    ID BIGINT NOT NULL,
    NOME CHARACTER VARYING (255) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    LOGRADOURO CHARACTER VARYING (255),
    CEP CHARACTER VARYING (9),
    CIDADE_ID BIGINT,
    CONSTRAINT OBSTACULO_PK PRIMARY KEY (ID),
    CONSTRAINT OBSTACULO_CIDADE_FK FOREIGN KEY (CIDADE_ID) REFERENCES OBSTACLES.CIDADE (ID)
);

CREATE SEQUENCE OBSTACLES.CIDADE_SEQUENCE;
CREATE SEQUENCE OBSTACLES.ESTADO_SEQUENCE;
CREATE SEQUENCE OBSTACLES.OBSTACULO_SEQUENCE;